# start and end date of the full plan4res results
# start date of output - Format: yyyy-mm-ddThh:mm+hh:mm  (+hh:mm express timezone)
BeginDataset: '2030-07-02T00:00+01:00'
DatasetTimestep: # duration of timestep (simulation timestep)
    Unit: days
    Duration: 1

# optional: dates on which to treat the output
BeginTreatData: '2030-07-02T00:00+01:00'
EndTreatData: '2031-06-30T23:00+01:00'

# directories
# dir: for reading results of plan4res : 
dir: 'data/local/Input_plan4res/results/' # repository where all results are in subdirectories mydirectory/variant/  or mydirectory/variant-option/

# variables for defining which treatments  will be done
map: yes   # if True: maps will be created ; only possible if geopandas is available
geopandas: yes # False if geopandas is not available; in that case , maps will be skiped

# Treatments to be performed
PostTreat:
    Volume: 
        read: yes  # reads volume outputs and create volume files to be used by 'draw' , 'latex' and 'iamc'
        draw: yes  # create graphs
        latex: yes  # write latex chapter
        iamc: yes  # convert outputs to openentrance format
        Dir: 'Volume/'  # outputs of plan4res for Volumes are in dir/variant-option/Volume/  => files VolumeOUTi.csv
    Flows: 
        read: yes # reads flows outputs and create volume files to be used by 'draw' , 'latex' and 'iamc'
        draw: yes
        latex: yes
        iamc: yes
        Dir: 'Flows/'
    Power:
        read: yes # reads volume outputs and create volume files to be used by 'draw' , 'latex', 'cmputecost' and 'iamc'
        computecost: yes  # compute variable costs
        draw: yes
        latex: yes
        iamc: yes
        Dir: 'ActivePower/'
    MarginalCost: 
        read: yes # reads volume outputs and create volume files to be used by 'draw' , 'latex' and 'iamc'
        draw: yes
        latex: yes
        iamc: yes
        update: yes  # compute "marginal cost" as the highest cost of started asset
        Dir: 'MarginalCosts/'
        max: 1000
    MarginalCostFlows:
        read: yes # reads volume outputs and create volume files to be used by 'draw' , 'latex' and 'iamc'
        draw: yes
        latex: yes
        iamc: yes
        Dir: 'MarginalCosts/'
    Demand:
        read: yes # reads volume outputs and create volume files to be used by 'draw' , 'latex' and 'iamc'
        draw: yes
        latex: yes
        iamc: yes
        Dir: 'Demand/'
    InstalledCapacity:
        draw: yes  # read output files from dir/OUT and creates hraphs in dir/IMG
        latex: yes # read output files in dir/OUT and graphs in dir/IMG and create a report in dir/Latex
        iamc: yes  # read output files and convert them to open entrance format in dir/IAMC
    SpecificPeriods: # optional - detailed treatments of specifis sub periods on specific scenarios
        read: yes    
        latex: yes
        iamc: yes
        draw: yes
        scenarios: [1] #subset of scenarios on which to perform detailed analysis on specific periods
        periods:
            myperiod1:       
                begin: '2030-07-02T00:00+01:00'
                end: '2030-07-08T23:00+01:00'
            # myperiod2:       
                # begin: '2030-12-09T00:00+01:00'
                # end: '2030-12-15T23:00+01:00'



# dimensions of graphics
Graphs:
    Volume: 
        nbcols: 3
        nblines: 3
        SizeCol: 50
        SizeRow: 50
        TitleSize: 50
        LabelSize: 40
    Power:
        treat: ['Hydro','Geothermal','Biomass','WindPower','Nuclear','PV','Hydrogen','Coal','Gaz','Oil'] # use if only a sublist of technos are in the graphs
        nbcols: 4
        nblines: 4
        SizeCol: 50
        SizeRow: 35
        TitleSize: 50
        LabelSize: 40
        ChloroGraph:
            nbcols: 4
            nblines: 4
            dpi: 50
    MarginalCost: 
        nbcols: 4
        nblines: 4
        SizeCol: 50
        SizeRow: 35
        TitleSize: 50
        LabelSize: 40
    MarginalCostFlows:
        nbcols: 3
        nblines: 9
    Demand:
        nbcols: 4
        nblines: 4
        SizeCol: 50
        SizeRow: 35
        TitleSize: 50
        LabelSize: 40

# name of scenario for the IAMC file
scenario: 'Fake Scenario'
model: 'plan4res v1.0'  # name of the model

# name and title of the latex report
namereport: 'nameofthereport'
titlereport: 'Title of the report'

# if bellman value is to be computed (file BellmanOUT.csv in inputs): yes, else: no
usevu: no
# SSVTimeStep number in BellmanOUT.csv corresponding to plot_end
timestepvusms: 14
# figures are rounded: 1, not rounded: 0
arrondi: 1
# min and max of the marginal cost graphs
marginalcostlimits:
    max: 10000
    min: -10000
pielimit: 0.001

# information per technology:
# color= hex code of the color to use for this technology
# the following should be read from the data
# cO2= cO2 cost per MWh for this technology
# varcost= Variable cost Euro per MWh for this technology
# startcost= Start-Up cost Euro

Technos:
    Geothermal:
        color: '#8FA600'
    Hydro|Run of River: 
        color: '#74DBDA'
    Nuclear:
        color: '#FFAA00'
    Coal|Hard coal|w/o CCS:
        color: '#0D0D0D'
    Coal|Hard coal|w/ CCS:  
        color: '#4D4F4F'
    Coal|Lignite|w/o CCS:
        color: '#2F3030'
    Wind|Offshore:
        color: '#2BFF00'
    Wind|Onshore:
        color: '#22CC00'
    Solar|PV:
        color: '#FFFF00'
    Biomass|w/ CCS:
        color: '#608000'
    Biomass|w/o CCS:
        color: '#608000'
    Hydrogen|OCGT:
        color: '#DF785B'
    Gas|CCGT|w/ CCS:
        color: '#FF0000'
    Gas|CCGT|w/o CCS:
        color: '#B30000'
    Gas|OCGT|w/o CCS:
        color: '#E00000'
    Oil|w/o CCS:
        color: '#4F0000'
    Reservoir:
        color: '#0000FF'
    Pumped Storage:
        color: '#3377FF'
    Lithium-Ion:
        color: '#D75BE1'
    Compressed Air:
        color: '#BB16C7'
    SlackUnit:
        color: '#FFFFFF'
    Pumped Storage_PUMP:
        color: '#3377FF'
    Lithium-Ion_PUMP:
        color: '#E68F67'
    Compressed Air_PUMP:
        color: '#E6847A'

# aggregated technologies (for aggregated graphs)
# for each aggr techno: list of technos and color codes 
technosAggr:
    Hydro:
        technos: ['Reservoir',  'Pumped Storage', 'Hydro|Run of River']
        color: blue
        colors: Blues
    Hydro_PUMP:
        technos: ['Pumped Storage_PUMP']
        color: blue
        colors: Blues
    Geothermal: 
        technos: ['Geothermal']
        color: olive
        colors: Greens
    WindPower:
        technos: ['Wind|Offshore', 'Wind|Onshore']
        color: green
        colors: Greens
    PV:
        technos: ['Solar|PV']
        color: yellow
        colors: YlOrRd
    Biomass: 
        technos: ['Biomass|w/ CCS','Biomass|w/o CCS']
        color: darkkhaki
        colors: Greens
    Nuclear:
        technos: ['Nuclear']
        color: orange
        colors: Oranges
    Hydrogen:
        technos: ['Hydrogen|OCGT']
        color: salmon
        colors: RdPu
    Coal:
        technos: ['Coal|Hard coal|w/o CCS','Coal|Hard coal|w/ CCS','Coal|Lignite|w/o CCS']
        color: black
        colors: Greys
    Gaz:
        technos: ['Gas|CCGT|w/o CCS','Gas|CCGT|w/ CCS','Gas|OCGT|w/o CCS']
        color: firebrick
        colors: Reds
    Battery: 
        technos: ['Compressed Air','Lithium-Ion']
        color: magenta
        colors: Purples
    Battery_PUMP: 
        technos: ['Compressed Air_PUMP','Lithium-Ion_PUMP']
        color: magenta
        colors: Purples
    Oil:
        technos: ['Oil|w/o CCS']
        color: saddlebrown
        colors: Greys
    Non Served:
        technos: ['SlackUnit']
        color: blueviolet
        colors: Purples
        
# lists of storage units
# pumping=list of units with pumping capacity
# nopumping=list of units without pumping capacity
pumping: [ 'Pumped Storage', 'Compressed Air','Lithium-Ion']
nopumping: [ 'Reservoir' ]

# specification of deterministic graphics for storages
graphVolumes:
    Reservoir: 
        Name: 'Reservoir' # name of graph
        Technos: ['Reservoir'] # technos included
    PumpedStorage: 
        Name: 'Pumped Storage'
        Technos: ['Pumped Storage']
    Battery: 
        Name: 'Batteries'
        Technos: ['Compressed Air','Lithium-Ion']

